### PR TITLE
#161776758 View all articles

### PR DESCRIPTION
**Pull request by mendozabree**
#### What does this PR do?

Allow all users to view articles
Create a dashboard for our application
#### Description of Task to be completed?

Currently, our application has no UI for viewing articles and a dashboard

This task sass allows us to create a dashboard and UI to view all articles

#### How should this be manually tested?

Run the application `npm start`
On the default page/ landing page of the application all articles are visible
Login and you should be able to see both the dashboard and all articles

#### What are the relevant pivotal tracker stories?

[#161776758](https://www.pivotaltracker.com/story/show/161776758)

#### Any background context you want to add?
N/A

#### Screenshots
image
image

## Checklist: I completed these to help reviewers

- [x] My IDE is configured to follow the [**ESlint Conventions**](https://github.com/eslint/eslint)

  No? Unsure? -> configure your IDE, format the code and add the changes with `git add . && git commit --amend`

- [x] I have **added tests** to cover my changes.

  No? -> write tests and add them to this commit `git add . && git commit --amend`

- [x] All new and existing **tests passed**.

  No? -> figure out why and add the fix to your commit. It is your responsibility to make sure your code works.

- [x] My pull request is **based on the latest changes** of the develop branch.

  No? Unsure? -> execute command `git pull --rebase origin develop`

### CODE REVIEW

**Comment by kakaemma** [comment]
@mendozabree, Kindly look into resolving the merge conflicts.

**Comment by kakaemma** [comment]
We were also advised to have one commit message. Please look into squashing the commits

**Comment by samuelbwambale** [comment]
@mendozabree You may have to delete the snapshots before pushing to the remote branch or add them to the `.gitignore` file

**Review by MuhanguziDavid — COMMENTED** [review]
Nice work @mendozabree . You could create an images folder and put all images there.

**Comment by mendozabree** [comment]
@samuelbwambale thanks for that the `__snapshots__` is from the develop branch I will fix it in this PR to remove them and my kind ask is that everyone with a PR up now should delete the file so it is not merged back to develop.
cc @MuhanguziDavid

**Comment by mendozabree** [comment]
@kakaemma the two commits are because I renamed the branch but I have fixed it now.

**Comment by mendozabree** [comment]
@MuhanguziDavid I have made the folder for images

**Review by samuelbwambale — APPROVED** [review]
LGTM

**Pull request merged**
