### PR TITLE
##160609508 Setup travis ci tool

### PR DESCRIPTION
**Pull request by RonKbS**
### What does this PR do?
Enables creation of test and code coverage on creating a PR.

#### Description of Task to be completed?
Currently, there is no travis check on commits pushed to this repo.
This task enables automatic building using travis.

#### How should this be manually tested?
On the `ch-travis-setup-160609508` branch, a badge is displayed showing whether the build is passing or not.

#### What are the relevant pivotal tracker stories?
[160609508](https://www.pivotaltracker.com/story/show/160609508)

### CODE REVIEW

**Review by mendozabree — APPROVED** [review]
LGTM

**Review by MuhanguziDavid — APPROVED** [review]
LGTM

**Review by samuelbwambale — APPROVED** [review]
Approved

**Comment by dondrzzy** [comment]
@RonKbS Address merge conflicts and update this PR to have all builds pass.

**Pull request merged**
